services:
    flyimg.mount_manager:
        class: League\Flysystem\MountManager

    League\Flysystem\MountManager: '@flyimg.mount_manager'

    Flyimg\App\ImageManipulator:
        autowire: true
        arguments:
            $mountManager: '@flyimg.mount_manager'
            $realPath: '%local_root_path%'
            $localPrefix: 'local'
            $storePrefix: 'store'

    flyimg.filesystem.local:
        class: League\Flysystem\Filesystem
        arguments:
            - '@flyimg.adapter.local'
        tags:
            - { name: flyimg.filesystem, alias: local }

    flyimg.filesystem.store:
        class: League\Flysystem\Filesystem
        arguments:
            - '@flyimg.adapter.store'
        tags:
            - { name: flyimg.filesystem, alias: store }
