home:
   path : /
   defaults: { _controller: 'Flyimg\App\Controller\DefaultController::indexAction' }

default_expression_upload:
   path : /upload/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.%default_adapter%::uploadAction', imageSrc: '' }
   requirements:
      imageSrc: .+

default_expression_get:
   path : /get/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.%default_adapter%::getAction', imageSrc: '' }
   requirements:
      imageSrc: .+

default_expression_path:
   path : /path/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.%default_adapter%::pathAction', imageSrc: '' }
   requirements:
      imageSrc: .+

cloudinary_expression_upload:
   path : /cloudinary/upload/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.cloudinary::uploadAction', imageSrc: '' }
   requirements:
      imageSrc: .+

cloudinary_expression_get:
   path : /cloudinary/get/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.cloudinary::getAction', imageSrc: '' }
   requirements:
      imageSrc: .+

cloudinary_expression_path:
   path : /cloudinary/path/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.cloudinary::pathAction', imageSrc: '' }
   requirements:
      imageSrc: .+

filter_expression_upload:
   path : /filter/upload/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.filter::uploadAction', imageSrc: '' }
   requirements:
      imageSrc: .+

filter_expression_path:
   path : /filter/path/{filtersSpec}/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.filter::pathAction', imageSrc: '' }
   requirements:
      imageSrc: .+

filter_expression_get:
   path: /filter/get/{imageSrc}
   defaults: { _controller: 'Flyimg\App\Controller\ContentDeliveryController.filter::getAction', imageSrc: '' }
   requirements:
      imageSrc: .+
